### ISSUE TITLE
Correções dos exercícios de nodejs

### ISSUE THREAD

**Issue by dbfernandes** [SaileSC/WebAcademy#1]
Node1: Resolução incompleta. Os arquivos são listados, mas não é possível visualizar o conteudo dos arquivos. Foi usado ES modules, mas era para ter usado CommonJs.
Node2: Tudo Ok.
Node3: Tudo Ok.

**Comment by SaileSC** [comment]
Boa tarde professor, desculpe meu erro, eu fiz as alterações.
